### ISSUE TITLE
Супер!

### ISSUE THREAD

**Issue by foshechka** [ifamed/slothMusic#1]
Хотелось бы еще, чтобы функционал расширялся. Например, возможность создавать плейлисты, загружать музыку в вк, поиск по жанрам музыки и т. д..

**Comment by foshechka** [comment]
Огромное спасибо, за такое дело! :+1:

**Comment by ifamed** [comment]
Сверх-функционала не обещаю, но буду стараться ;)

**Comment by foshechka** [comment]
Сейчас тестирую, супер! Спасибо! А можно сделать расширеный выбор скачивания: все выделенные или как-то в ручную по одному треку выделять?

**Comment by ifamed** [comment]
Да, при выборе "Режим загрузки", появляется справа иконка выбора всех аудиозаписей.
Насчет "16", то в данный момент решаю эту проблему. Это блокировка со стороны VK, при запросе заголовков и получении размера файла для подсчета битрейта.

**Comment by foshechka** [comment]
Ясно. А можно еще сделать, чтобы выбирать (отмечать) какие треки надо загрузить, а то если откроется страница с 300 треками сразу браузер ляжет.

**Comment by ifamed** [comment]
Такое возможно, при режиме загрузки.

**Comment by foshechka** [comment]
Будет ли реализована возможность на всякий случай ввода капчи, если вк начнет блокировать приложение?

**Comment by ifamed** [comment]
Насколько я знаю, тот функционал, что есть сейчас в этом не нуждается.
Если такая потребность возникнет, реализую.

**Comment by foshechka** [comment]
Хорошо, я понял. Благодарю! Успехов тебе в разработке! С нетерпением буду ждать обновлений и новых возможностей.

**Comment by ifamed** [comment]
Спасибо :)
